"use client";

import { ChangeEvent, FormEvent, useEffect, useMemo, useRef, useState } from "react";

type PriceItem={id:string;name:string;price:number;note:string};
type Product={id:string;name:string;price:number;description:string};
type Business={name:string;tagline:string;phone:string;whatsapp:string;address:string;mapQuery:string;hours:string};
const defaultBusiness:Business={name:"BARBERA",tagline:"הסטייל שלך. בדיוק שלך.",phone:"050-555-0198",whatsapp:"972505550198",address:"רחוב הרצל 24, ראשון לציון",mapQuery:"הרצל 24 ראשון לציון",hours:"א׳–ה׳ 09:00–20:00 · ו׳ 08:00–14:00"};
const defaultPrices:PriceItem[]=[{id:"p1",name:"תספורת גבר",price:70,note:"כולל עיצוב וגימור"},{id:"p2",name:"תספורת + זקן",price:95,note:"החבילה המלאה"},{id:"p3",name:"סידור זקן",price:45,note:"עיצוב, דירוג וגימור"},{id:"p4",name:"תספורת ילד",price:60,note:"עד גיל 12"}];
const defaultProducts:Product[]=[{id:"s1",name:"ווקס מט",price:55,description:"אחיזה חזקה ללא ברק"},{id:"s2",name:"שמן לזקן",price:65,description:"ריכוך, הזנה וריח נקי"},{id:"s3",name:"ספריי מלח",price:60,description:"נפח ומרקם טבעי"}];
const uid=()=>Math.random().toString(36).slice(2,9);
const money=(value:number)=>`${value.toLocaleString("he-IL")} ₪`;

export default function Home(){
 const [business,setBusiness]=useState(defaultBusiness),[prices,setPrices]=useState(defaultPrices),[products,setProducts]=useState(defaultProducts),[gallery,setGallery]=useState<string[]>([]);
 const [adminOpen,setAdminOpen]=useState(false),[activeTab,setActiveTab]=useState<"details"|"prices"|"products"|"gallery">("details"),[toast,setToast]=useState("");
 const fileInput=useRef<HTMLInputElement>(null);
 useEffect(()=>{const stored=localStorage.getItem("barbera-content-v1");if(stored){try{const p=JSON.parse(stored);if(p.business)setBusiness(p.business);if(p.prices)setPrices(p.prices);if(p.products)setProducts(p.products);if(p.gallery)setGallery(p.gallery)}catch{}}if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>undefined)},[]);
 useEffect(()=>{localStorage.setItem("barbera-content-v1",JSON.stringify({business,prices,products,gallery}))},[business,prices,products,gallery]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),2400);return()=>clearTimeout(t)},[toast]);
 const googleMaps=useMemo(()=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(business.mapQuery)}`,[business.mapQuery]);
 const waze=useMemo(()=>`https://waze.com/ul?q=${encodeURIComponent(business.mapQuery)}&navigate=yes`,[business.mapQuery]);
 function handleImages(e:ChangeEvent<HTMLInputElement>){const files=Array.from(e.target.files??[]).slice(0,Math.max(0,8-gallery.length));Promise.all(files.map(file=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file)}))).then(images=>{setGallery(current=>[...current,...images].slice(0,8));setToast("התמונות נשמרו במכשיר")}).catch(()=>setToast("לא הצלחנו לקרוא את התמונה"));e.target.value=""}
 function saveDetails(e:FormEvent<HTMLFormElement>){e.preventDefault();const v=new FormData(e.currentTarget);setBusiness({name:String(v.get("name")),tagline:String(v.get("tagline")),phone:String(v.get("phone")),whatsapp:String(v.get("whatsapp")),address:String(v.get("address")),mapQuery:String(v.get("mapQuery")),hours:String(v.get("hours"))});setToast("פרטי העסק נשמרו")}
 return <main>
  <header className="topbar"><a className="brand" href="#top"><span className="brand-mark">B</span><span>{business.name}</span></a><button className="admin-button" onClick={()=>setAdminOpen(true)}><span className="admin-dot"/>ניהול</button></header>
  <section className="hero" id="top"><div className="hero-copy"><span className="eyebrow">BARBER SHOP · EST. 2026</span><h1>{business.tagline}</h1><p>תספורת מדויקת, אווירה טובה ושירות שלא מעגל פינות.</p><div className="hero-actions"><a className="primary" href={`https://wa.me/${business.whatsapp}?text=${encodeURIComponent("היי, אשמח לקבוע תור")}`} target="_blank" rel="noreferrer">קביעת תור בוואטסאפ</a><a className="secondary" href={`tel:${business.phone}`}>התקשרו עכשיו</a></div></div><div className="hero-art"><div className="blade blade-one"/><div className="blade blade-two"/><div className="hero-badge"><strong>100%</strong><span>סטייל מקומי</span></div></div></section>
  <section className="trust-row"><div><strong>דיוק</strong><span>בכל קו וגימור</span></div><div><strong>אווירה</strong><span>קלילה ומקצועית</span></div><div><strong>מוצרים</strong><span>שבאמת עובדים</span></div></section>
  <section className="section" id="prices"><div className="section-heading"><div><span className="eyebrow">מחירון</span><h2>פשוט וברור.</h2></div><p>בלי הפתעות בקופה. בוחרים שירות ומגיעים להסתפר.</p></div><div className="price-list">{prices.map((item,index)=><article className="price-card" key={item.id}><span className="price-index">0{index+1}</span><div><h3>{item.name}</h3><p>{item.note}</p></div><strong>{money(item.price)}</strong></article>)}</div></section>
  <section className="section gallery-section" id="gallery"><div className="section-heading"><div><span className="eyebrow">מהכיסא שלנו</span><h2>התוצאות מדברות.</h2></div><button className="text-button" onClick={()=>{setActiveTab("gallery");setAdminOpen(true)}}>+ הוספת תמונות</button></div>{gallery.length?<div className="gallery-grid">{gallery.map((image,index)=><img key={index} src={image} alt={`עבודה מהגלריה ${index+1}`}/>)}</div>:<button className="empty-gallery" onClick={()=>{setActiveTab("gallery");setAdminOpen(true)}}><span>+</span><strong>הגלריה מחכה לעבודות שלך</strong><small>העלו עד 8 תמונות מהמכשיר</small></button>}</section>
  <section className="section products-section" id="products"><div className="section-heading"><div><span className="eyebrow">על המדף</span><h2>ממשיכים את הסטייל בבית.</h2></div></div><div className="product-grid">{products.map((product,index)=><article className="product-card" key={product.id}><div className={`product-visual tone-${index%3+1}`}><span>{product.name.slice(0,1)}</span></div><div className="product-copy"><div><h3>{product.name}</h3><p>{product.description}</p></div><strong>{money(product.price)}</strong></div></article>)}</div></section>
  <section className="location-section" id="location"><div className="location-card"><span className="eyebrow">איך מגיעים</span><h2>קפצו לביקור.</h2><p className="address">{business.address}</p><p>{business.hours}</p><div className="map-actions"><a className="primary" href={waze} target="_blank" rel="noreferrer">פתחו ב‑Waze</a><a className="secondary dark" href={googleMaps} target="_blank" rel="noreferrer">Google Maps</a></div></div><div className="map-pattern"><div className="pin">B</div><span className="road r1"/><span className="road r2"/><span className="road r3"/></div></section>
  <footer><div className="brand"><span className="brand-mark">B</span><span>{business.name}</span></div><p>הנתונים נשמרים מקומית במכשיר.</p></footer>
  {adminOpen&&<div className="modal-backdrop" onMouseDown={()=>setAdminOpen(false)}><section className="admin-panel" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><header><div><span className="eyebrow">עריכת תוכן</span><h2>ניהול האפליקציה</h2></div><button className="close" onClick={()=>setAdminOpen(false)}>×</button></header><nav className="admin-tabs">{([['details','פרטים'],['prices','מחירון'],['products','מוצרים'],['gallery','תמונות']] as const).map(([key,label])=><button key={key} className={activeTab===key?"active":""} onClick={()=>setActiveTab(key)}>{label}</button>)}</nav>
   {activeTab==="details"&&<form className="admin-form" onSubmit={saveDetails}><label>שם העסק<input name="name" defaultValue={business.name} required/></label><label>משפט ראשי<input name="tagline" defaultValue={business.tagline} required/></label><label>טלפון<input name="phone" defaultValue={business.phone} required/></label><label>מספר וואטסאפ (עם 972)<input name="whatsapp" defaultValue={business.whatsapp} required/></label><label>כתובת לתצוגה<input name="address" defaultValue={business.address} required/></label><label>כתובת לניווט<input name="mapQuery" defaultValue={business.mapQuery} required/></label><label>שעות פעילות<input name="hours" defaultValue={business.hours} required/></label><button className="primary full" type="submit">שמירת פרטים</button></form>}
   {activeTab==="prices"&&<div className="editor-list">{prices.map(item=><div className="editor-row" key={item.id}><div className="editor-fields"><input aria-label="שם שירות" value={item.name} onChange={e=>setPrices(list=>list.map(x=>x.id===item.id?{...x,name:e.target.value}:x))}/><input aria-label="תיאור שירות" value={item.note} onChange={e=>setPrices(list=>list.map(x=>x.id===item.id?{...x,note:e.target.value}:x))}/></div><input className="price-input" aria-label="מחיר" type="number" min="0" value={item.price} onChange={e=>setPrices(list=>list.map(x=>x.id===item.id?{...x,price:Number(e.target.value)}:x))}/><button className="remove" onClick={()=>setPrices(list=>list.filter(x=>x.id!==item.id))}>×</button></div>)}<button className="add-row" onClick={()=>setPrices(list=>[...list,{id:uid(),name:"שירות חדש",price:0,note:"תיאור קצר"}])}>+ הוספת שירות</button></div>}
   {activeTab==="products"&&<div className="editor-list">{products.map(item=><div className="editor-row" key={item.id}><div className="editor-fields"><input aria-label="שם מוצר" value={item.name} onChange={e=>setProducts(list=>list.map(x=>x.id===item.id?{...x,name:e.target.value}:x))}/><input aria-label="תיאור מוצר" value={item.description} onChange={e=>setProducts(list=>list.map(x=>x.id===item.id?{...x,description:e.target.value}:x))}/></div><input className="price-input" aria-label="מחיר" type="number" min="0" value={item.price} onChange={e=>setProducts(list=>list.map(x=>x.id===item.id?{...x,price:Number(e.target.value)}:x))}/><button className="remove" onClick={()=>setProducts(list=>list.filter(x=>x.id!==item.id))}>×</button></div>)}<button className="add-row" onClick={()=>setProducts(list=>[...list,{id:uid(),name:"מוצר חדש",price:0,description:"תיאור קצר"}])}>+ הוספת מוצר</button></div>}
   {activeTab==="gallery"&&<div className="gallery-editor"><input ref={fileInput} type="file" accept="image/*" multiple hidden onChange={handleImages}/><button className="upload-zone" onClick={()=>fileInput.current?.click()} disabled={gallery.length>=8}><span>↑</span><strong>{gallery.length>=8?"הגלריה מלאה":"בחירת תמונות מהמכשיר"}</strong><small>{gallery.length}/8 תמונות · נשמרות רק במכשיר הזה</small></button><div className="gallery-thumbs">{gallery.map((image,index)=><div key={index}><img src={image} alt=""/><button onClick={()=>setGallery(list=>list.filter((_,i)=>i!==index))}>×</button></div>)}</div></div>}
  </section></div>}{toast&&<div className="toast" role="status">{toast}</div>}
 </main>
}
