"use client";

import {ChangeEvent,FormEvent,useEffect,useMemo,useRef,useState} from "react";

type PriceItem={id:string;name:string;price:number;note:string};
type Product={id:string;name:string;price:number;description:string};
type Business={name:string;tagline:string;phone:string;whatsapp:string;address:string;mapQuery:string;hours:string};
type Tab="home"|"prices"|"gallery"|"products"|"appointments";
type Role="barber"|"client";
type Session={role:Role;phone:string};
type Appointment={id:string;clientPhone:string;service:string;date:string;time:string;status:"pending"|"confirmed"|"cancelled"};

const defaultBusiness:Business={name:"ARI COHEN",tagline:"אהלן, ארי כאן 👋🏻",phone:"",whatsapp:"",address:"שדרות רוטשילד 74, תל אביב",mapQuery:"שדרות רוטשילד 74 תל אביב",hours:"א׳–ה׳ 09:00–20:00 · ו׳ 08:00–14:00"};
const defaultPrices:PriceItem[]=[{id:"p1",name:"תספורת גבר",price:70,note:"כולל עיצוב וגימור"},{id:"p2",name:"תספורת + זקן",price:95,note:"החבילה המלאה"},{id:"p3",name:"סידור זקן",price:45,note:"עיצוב, דירוג וגימור"},{id:"p4",name:"תספורת ילד",price:60,note:"עד גיל 12"}];
const defaultProducts:Product[]=[{id:"s1",name:"ווקס מט",price:55,description:"אחיזה חזקה ללא ברק"},{id:"s2",name:"שמן לזקן",price:65,description:"ריכוך, הזנה וריח נקי"},{id:"s3",name:"ספריי מלח",price:60,description:"נפח ומרקם טבעי"}];
const demoPhoto="/barber-gallery-v1.png";
const defaultGallery=[demoPhoto,demoPhoto,demoPhoto,demoPhoto];
const uid=()=>Math.random().toString(36).slice(2,9);
const money=(value:number)=>`${value.toLocaleString("he-IL")} ₪`;
const icons={home:"⌂",prices:"₪",gallery:"▦",products:"◈",appointments:"◷",pin:"⌖",clock:"◷",phone:"⌕",back:"‹"};

function compressImage(file:File){return new Promise<string>((resolve,reject)=>{const image=new Image(),reader=new FileReader();reader.onload=()=>{image.onload=()=>{const max=960,scale=Math.min(1,max/Math.max(image.width,image.height)),canvas=document.createElement("canvas");canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext("2d")?.drawImage(image,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL("image/jpeg",.72))};image.onerror=reject;image.src=String(reader.result)};reader.onerror=reject;reader.readAsDataURL(file)})}

export default function Home(){
 const [business,setBusiness]=useState(defaultBusiness),[prices,setPrices]=useState(defaultPrices),[products,setProducts]=useState(defaultProducts),[gallery,setGallery]=useState<string[]>(defaultGallery);
 const [tab,setTab]=useState<Tab>("home"),[adminOpen,setAdminOpen]=useState(false),[bookingOpen,setBookingOpen]=useState(false),[toast,setToast]=useState("");
 const [session,setSession]=useState<Session|null>(null),[roleChoice,setRoleChoice]=useState<Role|null>(null),[appointments,setAppointments]=useState<Appointment[]>([]);
 const [adminTab,setAdminTab]=useState<"details"|"prices"|"products"|"gallery"|"broadcast">("details");
 const fileInput=useRef<HTMLInputElement>(null);
 useEffect(()=>{const stored=localStorage.getItem("barbera-content-v2")??localStorage.getItem("barbera-content-v1");if(stored){try{const p=JSON.parse(stored);if(p.business)setBusiness({...p.business,phone:p.business.phone==="050-555-0198"?"":p.business.phone,whatsapp:p.business.whatsapp==="972505550198"?"":p.business.whatsapp});if(p.prices)setPrices(p.prices);if(p.products)setProducts(p.products);if(p.gallery?.length)setGallery(p.gallery)}catch{}}try{const savedSession=localStorage.getItem("barbera-session"),savedAppointments=localStorage.getItem("barbera-appointments");if(savedSession)setSession(JSON.parse(savedSession));if(savedAppointments)setAppointments(JSON.parse(savedAppointments))}catch{}if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>undefined)},[]);
 useEffect(()=>{try{localStorage.setItem("barbera-content-v2",JSON.stringify({business,prices,products,gallery}))}catch{setToast("אין מספיק מקום לשמירת תמונות נוספות")}},[business,prices,products,gallery]);
 useEffect(()=>{try{localStorage.setItem("barbera-appointments",JSON.stringify(appointments))}catch{}},[appointments]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(""),2300);return()=>clearTimeout(timer)},[toast]);
 const mapUrl=useMemo(()=>`https://waze.com/ul?q=${encodeURIComponent(business.mapQuery)}&navigate=yes`,[business.mapQuery]);

 function openTab(next:Tab){setTab(next);window.scrollTo({top:0,behavior:"smooth"})}
 function handleImages(e:ChangeEvent<HTMLInputElement>){if(session?.role!=="barber"){e.target.value="";return}const files=Array.from(e.target.files??[]).slice(0,Math.max(0,8-gallery.length));Promise.all(files.map(compressImage)).then(images=>{setGallery(current=>[...current,...images].slice(0,8));setToast("התמונות נשמרו במכשיר")}).catch(()=>setToast("לא הצלחנו לקרוא את התמונה"));e.target.value=""}
 function saveDetails(e:FormEvent<HTMLFormElement>){e.preventDefault();if(session?.role!=="barber")return;const v=new FormData(e.currentTarget);setBusiness({name:String(v.get("name")),tagline:String(v.get("tagline")),phone:String(v.get("phone")),whatsapp:String(v.get("whatsapp")),address:String(v.get("address")),mapQuery:String(v.get("mapQuery")),hours:String(v.get("hours"))});setToast("פרטי העסק נשמרו")}
 function identify(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!roleChoice)return;const phone=String(new FormData(e.currentTarget).get("phone")??"").replace(/\D/g,"");if(phone.length<9){setToast("יש להזין מספר טלפון תקין");return}const next={role:roleChoice,phone};setSession(next);localStorage.setItem("barbera-session",JSON.stringify(next))}
 function signOut(){setSession(null);setRoleChoice(null);localStorage.removeItem("barbera-session");setTab("home")}
 function sendBooking(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!session)return;const v=new FormData(e.currentTarget),service=prices.find(item=>item.id===v.get("service"));const appointment:Appointment={id:uid(),clientPhone:session.phone,service:service?.name??"",date:String(v.get("date")),time:String(v.get("time")),status:"pending"};setAppointments(list=>[...list,appointment]);setBookingOpen(false);setToast("בקשת התור נשמרה ונשלחה לספר")}

 if(!session)return <main className="auth-shell">{toast&&<div className="toast">{toast}</div>}<div className="auth-brand"><span>A</span><strong>ARI COHEN</strong><small>BARBER STUDIO · TEL AVIV</small></div>{!roleChoice?<section className="role-card"><small>ברוכים הבאים</small><h1>איך תרצו להיכנס?</h1><p>בחרו את סוג החשבון כדי שנציג לכם רק את הכלים המתאימים.</p><button onClick={()=>setRoleChoice("client")}><i>♙</i><div><strong>כניסה כלקוח</strong><small>תורים, גלריה, מחירון ודרכי הגעה</small></div><b>‹</b></button><button onClick={()=>setRoleChoice("barber")}><i>✂</i><div><strong>כניסה כספר</strong><small>ניהול יומן, תוכן ולקוחות</small></div><b>‹</b></button></section>:<section className="phone-card"><button className="auth-back" onClick={()=>setRoleChoice(null)}>→</button><small>{roleChoice==="barber"?"כניסת ספר":"כניסת לקוח"}</small><h1>הזדהות עם הטלפון</h1><p>המספר ישמש לזיהוי החשבון והתורים שלך.</p><form onSubmit={identify}><label>מספר טלפון<input name="phone" type="tel" inputMode="tel" placeholder="05X-XXXXXXX" autoFocus required/></label><button className="black-button wide" type="submit">המשך</button></form><em>בדמו זה ההזדהות מתבצעת ללא SMS.</em></section>}</main>;

 return <main className="app-shell">
  <header className="app-header"><button className="mini-logo" onClick={()=>openTab("home")}>A</button><strong>{business.name}</strong><button className="manage-link" onClick={session.role==="barber"?()=>setAdminOpen(true):signOut}>{session.role==="barber"?"ניהול":"יציאה"}</button></header>

  {tab==="home"&&<div className="screen home-screen">
   <section className={`cover ${gallery[0]?"has-photo":"default-cover"} ${gallery[0]===demoPhoto?"preset-cover":""}`} style={gallery[0]?{backgroundImage:`linear-gradient(180deg,transparent 40%,rgba(0,0,0,.45)),url(${gallery[0]})`}:{backgroundImage:"linear-gradient(180deg,transparent 45%,rgba(0,0,0,.5)),url(/og.jpg)"}}/>
   <section className="quick-actions">
    <a href={mapUrl} target="_blank" rel="noreferrer"><i>{icons.pin}</i><span>איך מגיעים</span></a>
    <button onClick={()=>{setToast(business.hours)}}><i>{icons.clock}</i><span>שעות פעילות</span></button>
    {business.phone?<a href={`tel:${business.phone}`}><i>{icons.phone}</i><span>דברו איתנו</span></a>:<button onClick={()=>setToast("מספר הטלפון יעודכן בקרוב")}><i>{icons.phone}</i><span>דברו איתנו</span></button>}
   </section>
   <section className="welcome-card"><h1>{session.role==="barber"?"בוקר טוב, הספרייה שלך מוכנה":business.tagline}</h1><p>{session.role==="barber"?`${appointments.filter(a=>a.status!=="cancelled").length} תורים במערכת · אפשר לנהל הכל מכאן.`:"הגיע הזמן להתחדש. בחרו שירות, תאריך ושעה פנויה."}</p><button className="black-button" onClick={session.role==="barber"?()=>openTab("appointments"):()=>setBookingOpen(true)}>{session.role==="barber"?"פתיחת מערכת התורים":"קביעת תור"}</button></section>
   <section className="feature-card" onClick={()=>openTab("gallery")} role="button" tabIndex={0}>
    {gallery[1]?<div className={`feature-photo ${gallery[1]===demoPhoto?"preset-photo preset-2":""}`} style={{backgroundImage:`url(${gallery[1]})`}} role="img" aria-label="עבודה מהמספרה"/>:<div className="feature-placeholder"><span>✂</span></div>}
    <div><span>העבודות שלנו</span><h2>קצת עלינו</h2><p>הציצו בגלריה והכירו את הסגנון שלנו.</p></div>
   </section>
   <section className="home-price-preview"><div className="section-title"><div><span>השירותים שלנו</span><h2>מה מתאים לך?</h2></div><button onClick={()=>openTab("prices")}>לכל המחירון</button></div>{prices.slice(0,3).map(item=><div className="service-row" key={item.id}><div><strong>{item.name}</strong><small>{item.note}</small></div><b>{money(item.price)}</b></div>)}</section>
  </div>}

  {tab==="prices"&&<div className="screen"><PageTitle title="מחירון" subtitle="כל השירותים, בלי הפתעות" onBack={()=>openTab("home")}/><section className="list-section">{prices.map((item,index)=><article className="list-card" key={item.id}><span className="number">{String(index+1).padStart(2,"0")}</span><div><h3>{item.name}</h3><p>{item.note}</p></div><strong>{money(item.price)}</strong></article>)}<button className="black-button wide" onClick={()=>setBookingOpen(true)}>קביעת תור</button></section></div>}
  {tab==="gallery"&&<div className="screen"><PageTitle title="הגלריה" subtitle="תיק העבודות של ארי" onBack={()=>openTab("home")}/>{gallery.length?<section className="photo-grid">{gallery.map((image,index)=><div key={index} className={`gallery-photo ${image===demoPhoto?`preset-photo preset-${index%4+1}`:""}`} style={{backgroundImage:`url(${image})`}} role="img" aria-label={`עבודה ${index+1}`}/>)}</section>:<section className="empty-state"><span>▦</span><h2>עוד אין כאן תמונות</h2><p>{session.role==="barber"?"הוסיפו עבודות דרך אזור הניהול והן יופיעו כאן.":"הספר יעדכן כאן עבודות חדשות בקרוב."}</p>{session.role==="barber"&&<button className="outline-button" onClick={()=>{setAdminTab("gallery");setAdminOpen(true)}}>הוספת תמונות</button>}</section>}</div>}
  {tab==="products"&&<div className="screen"><PageTitle title="המוצרים שלנו" subtitle="להמשיך את הלוק גם בבית" onBack={()=>openTab("home")}/><section className="products-grid">{products.map((product,index)=><article className="product-card" key={product.id}><div className={`product-art tone-${index%3+1}`}><span>{product.name.slice(0,1)}</span></div><div><h3>{product.name}</h3><p>{product.description}</p><strong>{money(product.price)}</strong></div></article>)}</section></div>}

  {tab==="appointments"&&<div className="screen"><PageTitle title={session.role==="barber"?"מערכת התורים":"התורים שלי"} subtitle={session.role==="barber"?"ניהול בקשות ולוח העבודה":"צפייה וביטול תורים"} onBack={()=>openTab("home")}/><section className="appointments-list">{appointments.filter(a=>session.role==="barber"||a.clientPhone===session.phone).length?appointments.filter(a=>session.role==="barber"||a.clientPhone===session.phone).map(item=><article className={`appointment-card ${item.status}`} key={item.id}><div className="appointment-date"><b>{item.time}</b><small>{item.date}</small></div><div><h3>{item.service}</h3><p>{session.role==="barber"?`לקוח · ${item.clientPhone}`:item.status==="confirmed"?"התור אושר":"ממתין לאישור הספר"}</p></div><div className="appointment-actions">{session.role==="barber"&&item.status==="pending"&&<button onClick={()=>setAppointments(list=>list.map(a=>a.id===item.id?{...a,status:"confirmed"}:a))}>אישור</button>}<button onClick={()=>setAppointments(list=>list.map(a=>a.id===item.id?{...a,status:"cancelled"}:a))} disabled={item.status==="cancelled"}>ביטול</button></div></article>):<div className="empty-state"><span>◷</span><h2>אין תורים כרגע</h2><p>{session.role==="barber"?"בקשות חדשות יופיעו כאן.":"אפשר לבחור תור חדש לפי השעות הפנויות."}</p>{session.role==="client"&&<button className="black-button" onClick={()=>setBookingOpen(true)}>קביעת תור</button>}</div>}</section></div>}

  <nav className="bottom-nav" aria-label="ניווט ראשי">{(session.role==="barber"?[['home','בית'],['appointments','תורים'],['gallery','גלריה'],['products','מוצרים']]:[['home','בית'],['prices','מחירון'],['appointments','התורים שלי'],['gallery','גלריה']] as [Tab,string][]).map(([key,label])=><button key={key} className={tab===key?"active":""} onClick={()=>openTab(key)}><i>{icons[key]}</i><span>{label}</span></button>)}</nav>

  {bookingOpen&&<div className="sheet-backdrop" onMouseDown={()=>setBookingOpen(false)}><section className="bottom-sheet" onMouseDown={e=>e.stopPropagation()}><div className="sheet-handle"/><header><div><small>מתחדשים?</small><h2>קביעת תור</h2></div><button onClick={()=>setBookingOpen(false)}>×</button></header><form className="booking-form" onSubmit={sendBooking}><label>בחרו שירות<select name="service" required>{prices.map(item=><option key={item.id} value={item.id}>{item.name} · {money(item.price)}</option>)}</select></label><div className="form-row"><label>תאריך<input name="date" type="date" min={new Date().toISOString().slice(0,10)} required/></label><label>שעה מועדפת<input name="time" type="time" required/></label></div><p>הבקשה תישלח ל‑WhatsApp והמספרה תאשר את השעה.</p><button className="black-button wide" type="submit">שליחת בקשה ב‑WhatsApp</button></form></section></div>}

  {session.role==="barber"&&adminOpen&&<div className="sheet-backdrop admin-backdrop" onMouseDown={()=>setAdminOpen(false)}><section className="admin-panel" onMouseDown={e=>e.stopPropagation()}><header><div><small>אזור ספר</small><h2>ניהול האפליקציה</h2></div><button onClick={()=>setAdminOpen(false)}>×</button></header><nav className="admin-tabs">{([['details','פרטים'],['prices','מחירון'],['products','מוצרים'],['gallery','תמונות'],['broadcast','תפוצה']] as const).map(([key,label])=><button key={key} className={adminTab===key?"active":""} onClick={()=>setAdminTab(key)}>{label}</button>)}</nav>
   {adminTab==="details"&&<form className="admin-form" onSubmit={saveDetails}><label>שם העסק<input name="name" defaultValue={business.name} required/></label><label>משפט פתיחה<input name="tagline" defaultValue={business.tagline} required/></label><label>טלפון<input name="phone" defaultValue={business.phone} required/></label><label>מספר WhatsApp עם 972<input name="whatsapp" defaultValue={business.whatsapp} required/></label><label>כתובת לתצוגה<input name="address" defaultValue={business.address} required/></label><label>כתובת לניווט<input name="mapQuery" defaultValue={business.mapQuery} required/></label><label>שעות פעילות<input name="hours" defaultValue={business.hours} required/></label><button className="black-button wide" type="submit">שמירת פרטים</button></form>}
   {adminTab==="prices"&&<EditorList items={prices} setItems={setPrices} kind="price"/>}
   {adminTab==="products"&&<EditorList items={products} setItems={setProducts} kind="product"/>}
   {adminTab==="gallery"&&<div className="gallery-editor"><input ref={fileInput} type="file" accept="image/*" multiple hidden onChange={handleImages}/><button className="upload-zone" onClick={()=>fileInput.current?.click()} disabled={gallery.length>=8}><span>＋</span><strong>{gallery.length>=8?"הגלריה מלאה":"בחירת תמונות מהמכשיר"}</strong><small>{gallery.length}/8 תמונות · התמונה הראשונה היא תמונת השער</small></button><div className="gallery-thumbs">{gallery.map((image,index)=><div key={index}><img src={image} alt=""/><button onClick={()=>setGallery(list=>list.filter((_,i)=>i!==index))}>×</button></div>)}</div></div>}
   {adminTab==="broadcast"&&<form className="broadcast-form" onSubmit={e=>{e.preventDefault();setToast(`הודעת הדמו הוכנה עבור ${new Set(appointments.map(a=>a.clientPhone)).size} לקוחות`);(e.currentTarget.elements.namedItem("message") as HTMLTextAreaElement).value=""}}><div className="broadcast-stat"><strong>{new Set(appointments.map(a=>a.clientPhone)).size}</strong><span>לקוחות רשומים לקבלת עדכונים</span></div><label>הודעה ללקוחות<textarea name="message" rows={5} placeholder="לדוגמה: התפנה תור היום בשעה 18:00" required/></label><p>בגרסת הדמו ההודעה אינה נשלחת בפועל ואינה כרוכה בעלות.</p><button className="black-button wide" type="submit">הכנת הודעת תפוצה</button><button className="outline-button wide" type="button" onClick={signOut}>יציאה מחשבון הספר</button></form>}
  </section></div>}
  {toast&&<div className="toast">{toast}</div>}
 </main>
}

function PageTitle({title,subtitle,onBack}:{title:string;subtitle:string;onBack:()=>void}){return <header className="page-title"><button onClick={onBack} aria-label="חזרה">‹</button><div><small>{subtitle}</small><h1>{title}</h1></div><span/></header>}

function EditorList({items,setItems,kind}:{items:(PriceItem|Product)[];setItems:React.Dispatch<React.SetStateAction<any[]>>;kind:"price"|"product"}){return <div className="editor-list">{items.map(item=><div className="editor-row" key={item.id}><div><input value={item.name} onChange={e=>setItems(list=>list.map(x=>x.id===item.id?{...x,name:e.target.value}:x))}/><input value={kind==="price"?(item as PriceItem).note:(item as Product).description} onChange={e=>setItems(list=>list.map(x=>x.id===item.id?{...x,[kind==="price"?"note":"description"]:e.target.value}:x))}/></div><input className="price-input" type="number" value={item.price} onChange={e=>setItems(list=>list.map(x=>x.id===item.id?{...x,price:Number(e.target.value)}:x))}/><button className="remove" onClick={()=>setItems(list=>list.filter(x=>x.id!==item.id))}>×</button></div>)}<button className="add-row" onClick={()=>setItems(list=>[...list,kind==="price"?{id:uid(),name:"שירות חדש",price:0,note:"תיאור קצר"}:{id:uid(),name:"מוצר חדש",price:0,description:"תיאור קצר"}])}>+ הוספה חדשה</button></div>}
